version: "3"
services:
  mysql:
    container_name: memo_database
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fw190_watching_you
    volumes:
      - memo_db:/var/lib/mysql
    networks:
      - memo_net
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000-8002:8000"
    env_file:
      - .env
    volumes:
      - ./memo_logs:/memo/logs
    networks:
      - memo_net
  frontpage:
    container_name: memo_nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/data/www/html/index.html:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - memo_net

volumes:
  memo_db:
    driver: local

networks:
  memo_net:
    driver: bridge