name: Memo Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
	        host: ${{ secrets.SERVER_HOST }}
			username: ${{ secrets.SERVER_USER }}
			key: ${{ secrets.SERVER_SSH_KEY }}
			port: ${{ secrets.SERVER_PORT }}
			script: |
				cd /home/fphedry/memo
				git pull origin main
				./rolling_update.sh
